[workspace]
members=[
  "auction/program",
  "metaplex/program",
  "token-vault/program",
  "token-vault/test/",
  "token-metadata/program",
  "token-metadata/test",
  "programs/*",
  "nft-packs/program",
  "nft-packs/tests"
]
exclude = []
