name: SDK Auction House

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-lint-and-test-fair-launch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/yarn-install-and-verify
        with:
          cache_id: sdk-fair-launch
          working_dir: ./fair-launch/js
          skip_test: true
